#theme: jekyll-theme-slate
title: Weasel
logo: "/media/uni-sheffield-logo.png"
#og_image: "/media/uni-sheffield-logo.png"
#teaser: "/media/uni-sheffield-logo.png"
#avatar: "/media/uni-sheffield-logo-16.ico"
remote_theme: pmarsceill/just-the-docs
color_scheme: weasel
heading_anchors: true
nav_sort: case_sensitive

# Aux links for the upper right navigation
aux_links:
  "Weasel on GitHub":
    - "//github.com/QIB-Sheffield/WEASEL"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2020 Steven Shillitoe, Joao Sousa and Steven Sourbron. Distributed by an <a href=\"https://github.com/QIB-Sheffield/WEASEL/blob/master/LICENSE\">Apache 2.0 license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/QIB-Sheffield/WEASEL" # the github URL for your repo

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-spaceship
  - jekyll-archives